name: newloginsystem
main: apartkktrain\login\Main
version: 1.0.0
api: 3.12.0
auther: apartkktrain

commands:

  register:
     description: サーバーにMinecraftのID並びにアカウントを登録します。
     usage: /register

  login:
     description: サーバーに再度ログインします。(アカウント登録コマンドではありません。)
     usage : /login
